### Ньяти Каелиле БВТ2201 - Лаб 2

#### Optimization

In [1]:
import cv2 as cv
import numpy as np

In [14]:
img = cv.imread('image5.jpg')
assert img is not None, "file could not be read, check with os.path.exists()"
e1 = cv.getTickCount()
for i in range(5,49,2):
    img = cv.medianBlur(img,i)
e2 = cv.getTickCount()
t = (e2 - e1)/cv.getTickFrequency()
print( t )


cv.useOptimized()
cv.setUseOptimized(False)

0.1010365


In [16]:
# check if optimization is enabled
cv.useOptimized()
timeit1 = cv.medianBlur(img,49)
print("timeit1: ", timeit1)

cv.setUseOptimized(False)
cv.useOptimized()
timeit2 = cv.medianBlur(img,49)
print("timeit2: ", timeit2)

timeit1:  [[[191 129  93]
  [191 129  93]
  [191 129  93]
  ...
  [137 128 113]
  [137 128 109]
  [137 128 109]]

 [[191 129  93]
  [191 129  93]
  [191 129  93]
  ...
  [137 128 113]
  [137 128 113]
  [137 128 109]]

 [[191 129  93]
  [191 129  93]
  [191 129  93]
  ...
  [137 128 113]
  [137 128 113]
  [137 128 109]]

 ...

 [[194 133  89]
  [194 133  89]
  [194 133  89]
  ...
  [186 128  93]
  [186 128  93]
  [186 128  93]]

 [[186 128  89]
  [186 128  89]
  [186 128  89]
  ...
  [186 128  93]
  [186 128  93]
  [186 128  93]]

 [[186 128  89]
  [186 128  89]
  [186 128  89]
  ...
  [186 128  93]
  [186 128  93]
  [185 128  93]]]
timeit2:  [[[191 129  93]
  [191 129  93]
  [191 129  93]
  ...
  [137 128 113]
  [137 128 109]
  [137 128 109]]

 [[191 129  93]
  [191 129  93]
  [191 129  93]
  ...
  [137 128 113]
  [137 128 113]
  [137 128 109]]

 [[191 129  93]
  [191 129  93]
  [191 129  93]
  ...
  [137 128 113]
  [137 128 113]
  [137 128 109]]

 ...

 [[194 133  89]
  [194 133  89]


In [23]:
# Convert the image to grayscale
gray_img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

# Count non-zero pixels using OpenCV
timeit1 = cv.countNonZero(gray_img) #this one is faster

# Count non-zero pixels using NumPy
timeit2 = np.count_nonzero(img)

print("OpenCV countNonZero:", timeit1)
print("NumPy count_nonzero:", timeit2)

OpenCV countNonZero: 50290
NumPy count_nonzero: 150870


#### Exercise 2

##### Video capture

In [28]:
import numpy as np
import cv2 as cv

cap = cv.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Our operations on the frame come here
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv.imshow('frame', gray)
    if cv.waitKey(1) == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv.destroyAllWindows()

KeyboardInterrupt: 

#### Video from files

In [35]:
import numpy as np
import cv2 as cv

cap = cv.VideoCapture(r'C:\Users\khaye\Videos\Captures\demo2.mp4')

while cap.isOpened():
    ret, frame = cap.read()

    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)

    cv.imshow('frame', gray)
    if cv.waitKey(1) == ord('q'):
        break

cap.release()
cv.destroyAllWindows()

Can't receive frame (stream end?). Exiting ...


#### Saving a video

In [ ]:
import numpy as np
import cv2 as cv

cap = cv.VideoCapture(0)

# Define the codec and create VideoWriter object
fourcc = cv.VideoWriter_fourcc(*'DIVX')
out = cv.VideoWriter('output.mp4', fourcc, 20.0, (640,  480))

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    frame = cv.flip(frame, 0)

    # write the flipped frame
    out.write(frame)

    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break

# Release everything if job is finished
cap.release()
out.release()
cv.destroyAllWindows()